-- People often copy jobs. When they do, the GM table does not exist anymore.
-- This line makes the job code work both inside and outside of gamemode files.
-- You should not copy this line into your code.
local GAMEMODE = GAMEMODE or GM
--[[--------------------------------------------------------
Default teams. Please do not edit this file. Please use the LynxonsRPmod addon instead.
--------------------------------------------------------]]

--[[==================================================================
=============================== Работы ===============================
======================================================================]]
LYNX_CITIZEN = LynxonsRP.createJob("Гражданский", {
    color = Color(76, 230, 79),
    model = {
          "models/player/group03/male_06.mdl"
    },
    description = [[
        Описания
    ]],
    weapons = {},
    command = "citizen",
    max = 0,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    cook = true,
    canSee = fp{fn.Id, true},
    category = "Гражданские",
})

LYNX_MAYOR = LynxonsRP.createJob("Мэр города", {
    color = Color(76, 230, 79),
    model = {
        "models/player/gman_high.mdl",
        "models/player/breen.mdl"
    },
    description = [[
        Описание
    ]],
    weapons = {},
    command = "mayor",
    max = 1,
    salary = 0,
    admin = 0,
    vote = true,
    hasLicense = true,
    mayor = true,
    category = "Департамент администрации города",
    canDemote = false,
    canSee = fp{fn.Id, true},
    PlayerDeath = function(ply, weapon, killer)
        ply:teamBan()
        ply:changeTeam(GAMEMODE.DefaultTeam, true)
        LynxonsRP.notifyAll(0, 4, "Мэр покинул свой пост") 
    end,
})

LYNX_MEDIC = LynxonsRP.createJob("Медик", {
    color = Color(47, 79, 79, 255),
    model = "models/player/kleiner.mdl",
    description = [[
        Описание
    ]],
    command = "medic",
    max = 0,
    salary = 0,
    admin = 0,
    vote = false,
    hasLicense = false,
    medic = true,
    category = "Местное отделение больницы",
})

LYNX_POLICE = LynxonsRP.createJob("Департамент полиции города", {
    color = Color(47, 79, 79, 255),
    model = "models/player/kleiner.mdl",
    description = [[
        Описание
    ]],
    command = "police",
    max = 0,
    salary = 0,
    admin = 0,
    vote = false,
    hasLicense = false,
    chief = true,
    hasLicense = true,
    category = "Местное отделение больницы",
})


--[[==================================================================
============================ Двери ===================================
======================================================================]]
AddDoorGroup("Гражданские", LYNX_CITIZEN)
AddDoorGroup("Департамент полиции города", LYNX_POLICE)
AddDoorGroup("Полиция тихого района", LYNX_POLICE)
AddDoorGroup("Госпиталь", LYNX_MEDIC)
AddDoorGroup("Департамент администрации города", LYNX_MEDIC, LYNX_POLICE, LYNX_MAYOR)
AddDoorGroup("Служба быстрого реагирования и по борьбе с терроризмом", LYNX_POLICE)
AddDoorGroup("Управление по борьбе с наркотиками", LYNX_POLICE)
AddDoorGroup("Служба маршалов", LYNX_POLICE)

-- Group chats
LynxonsRP.createGroupChat(function(ply) return ply:isCP() end)
-- LynxonsRP.createGroupChat(TEAM_MOB, TEAM_GANG)
LynxonsRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)

-- Initial team when first spawning
GAMEMODE.DefaultTeam = LYNX_CITIZEN

-- Teams that belong to Civil Protection
GAMEMODE.CivilProtection = {
    [LYNX_POLICE] = true,
    [LYNX_MEDIC] = true,
    [LYNX_MAYOR] = true,
}

--[[==================================================================
=========================== Понижение ================================
======================================================================]]
LynxonsRP.createDemoteGroup("Департамент полиции города", {LYNX_POLICE})
LynxonsRP.createDemoteGroup("Полиция тихого района", {LYNX_POLICE})




--[[==================================================================
=========================== Дефолт ===================================
======================================================================]]
LynxonsRP.createCategory {
    name = "Гражданские",
    categorises = "jobs",
    startExpanded = true,
    color = Color(114, 107, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 1,
}

--[[==================================================================
=========================== Работы ===================================
======================================================================]]
LynxonsRP.createCategory {
    name = "Департамент полиции города",
    categorises = "jobs",
    startExpanded = true,
    color = Color(114, 107, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 2,
}
LynxonsRP.createCategory {
    name = "Полиция тихого района",
    categorises = "jobs",
    startExpanded = true,
    color = Color(114, 107, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 3,
}
LynxonsRP.createCategory {
    name = "Местное отделение больницы",
    categorises = "jobs",
    startExpanded = true,
    color = Color(114, 107, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 4,
}
LynxonsRP.createCategory {
    name = "Департамент администрации города",
    categorises = "jobs",
    startExpanded = true,
    color = Color(114, 107, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 5,
}
LynxonsRP.createCategory {
    name = "Служба быстрого реагирования и по борьбе с терроризмом",
    categorises = "jobs",
    startExpanded = true,
    color = Color(114, 107, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 7,
}
LynxonsRP.createCategory {
    name = "Управление по борьбе с наркотиками",
    categorises = "jobs",
    startExpanded = true,
    color = Color(114, 107, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 8,
}
LynxonsRP.createCategory {
    name = "Служба маршалов",
    categorises = "jobs",
    startExpanded = true,
    color = Color(114, 107, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 9,
}

--[[==================================================================
=========================== Администрация ============================
======================================================================]]
LynxonsRP.createCategory {
    name = "Администрация",
    categorises = "jobs",
    startExpanded = true,
    color = Color(114, 107, 255),
    sortOrder = 10,
    canSee = function(ply) 
        return table.HasValue({"superadmin", "admin"}, ply:GetUserGroup()) 
   end,
}

LynxonsRP.createCategory{
    name = "Other",
    categorises = "jobs",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 255,
}
